sigstore, test: break apart DSSE/artifact sign APIs
sigstore/sigstore-python pull request #956
Opened 2024-04-03 16:55 UTC by woodruffw

Per https://github.com/sigstore/sigstore-python/issues/628: this turns `sign(...)` into `sign_artifact(...)` and `sign_intoto(...)` respectively. In doing so, we're also able to simplify and deduplicate the internals of the `Signer` class a bit.

2024-04-05 08:15 UTC, jku requested changes
I think this looks good. I just have docstring and changelog nitpicks.

The changelog rewrite could be left as its own issue: we'll need to review it anyway since you've done so much on this release.

2024-04-05 08:15 UTC, jku commented on sigstore/sign.py
>          a DSSE envelope and corresponding `dsse` entry within the bundle.
looks like this needs a rewrite still

2024-04-05 08:15 UTC, jku commented on CHANGELOG.md
> +  ([#862](https://github.com/sigstore/sigstore-python/pull/862))
I suppose this can just be removed since we already mention that `sign_artifact` has been added above.

2024-04-05 08:15 UTC, jku commented on CHANGELOG.md
> +  is unchanged ([#921](https://github.com/sigstore/sigstore-python/pull/921))
I suppose this can just be removed since we already mention that `sign_artifact` has been added above.

2024-04-05 08:15 UTC, jku commented on CHANGELOG.md
>    ([#860](https://github.com/sigstore/sigstore-python/pull/860))
This should really talk about `Signer.sign_artifact()` as a brand new method (and could mention how it's a replacement for removed `Signer.sign()`)

2024-04-05 15:42 UTC, woodruffw commented
> The changelog rewrite could be left as its own issue: we'll need to review it anyway since you've done so much on this release.

Yeah, good call. I'll stop updating it with these PRs and file a separate tracker for doing a big update pre-release 🙂

2024-04-12 13:17 UTC, jku approved these changes

2024-04-12 14:05 UTC, merged